// All translatable page copy, in English (en) and Sinhala (si).
// Structural data that doesn't change per language (image slugs, icons,
// counter targets) lives in data/site.js.

export const CONTENT = {
  en: {
    code: "en",
    label: "EN",
    other: "සිං",
    nav: { place: "The Place", amenities: "Amenities", gallery: "Gallery", booking: "Booking", book: "Book a stay" },
    hero: {
      eyebrow: "Kandy · Sri Lanka",
      titleWords: ["Wake", "up", "in", "the"],
      titleEm: "green.",
      lead: "A small homestay up in the Kandy hills. There's a pool with lights strung through the trees, a badminton court out back, and green pretty much everywhere you look. Come do nothing for a few days.",
      chips: { pool: "Pool free with booking", badminton: "Badminton court", gardens: "Gardens & murals" },
      ctaPrimary: "Check availability",
      ctaSecondary: "See the place",
      scroll: "Scroll",
    },
    about: {
      eyebrow: "The place",
      title: "Mostly green, mostly quiet",
      lead: "We wanted a place where the outside doesn't stop at the door. So there's ivy over the windows, lanterns that come on after dark, and a pool that sits lit up under the trees once the evening sets in.",
      muted: "It's small on purpose. A few rooms, a garden to wander, and quiet enough that the birds wake you before your alarm does.",
      points: [
        "Tree murals on the walls and plants in every corner",
        "A long pool that's yours the whole stay, no extra charge",
        "Cool green rooms that are actually easy to sleep in",
        "About ten minutes from Kandy town",
      ],
      tag: "Blue hour by the pool",
    },
    amenities: {
      eyebrow: "What you get",
      title: "Everything for an easy stay",
      lead: "The pool and the court come with your booking. The kitchen's there if you feel like cooking. That's about it, really.",
      items: [
        { icon: "pool", badgeTone: "good", title: "Freshwater Pool", badge: "Free with booking", body: "A long pool with lights strung around it and palms behind. It's free with your stay, so swim at six in the morning or at midnight, whenever suits you." },
        { icon: "racket", badgeTone: "good", title: "Badminton Court", badge: "Included", body: "An open court out back. We keep rackets and a shuttle around, so grab a game once it cools down in the evening." },
        { icon: "kitchen", badgeTone: "info", title: "Shared Kitchen", badge: "Small extra charge", body: "There's a full kitchen if you'd rather cook your own food. Just ask when you book; it's a small extra. Handy if you're staying a while." },
        { icon: "lantern", badgeTone: "plain", title: "Fairy-lit Dining Deck", badge: "Every evening", body: "A covered deck under the round woven lanterns. It's where most evenings end up, over dinner or a slow game of cards." },
        { icon: "leaf", badgeTone: "plain", title: "Gardens & Murals", badge: "All around you", body: "Tree murals, ferns in pots, and lights pointed up into the leaves. There's something green wherever you turn." },
        { icon: "bed", badgeTone: "plain", title: "Leafy Rooms", badge: "Calm & quiet", body: "Green walls, soft light, a bit of ivy by the window. They stay cool and quiet, which is what you want after a day out walking." },
      ],
    },
    stats: [
      { to: 6, suffix: "", label: "Spaces & amenities" },
      { to: 2, suffix: "", label: "Outdoor activities" },
      { to: 100, suffix: "%", label: "Surrounded by green" },
    ],
    gallery: {
      eyebrow: "Look around",
      title: "A few corners of the place",
      lead: "Actual photos, just brightened up a bit. Tap one to see it bigger.",
      captions: {
        "pool-twilight": "The pool at twilight",
        "pool-fairy-night": "Fairy lights over the pool",
        "pool-dusk": "Pool, lit up at dusk",
        "pool-day": "The lap pool by day",
        "pool-night": "Blue hour by the water",
        mural: "The signature tree mural",
        "room-green": "A forest-green room",
        "room-jungle": "A room with a jungle view",
        "room-pink": "Bright drapes, green walls",
        "dining-nook": "The dining corner",
        dining: "Dinner under the lanterns",
        "lounge-1": "The lounge",
        "lounge-2": "Room to gather",
        "lounge-3": "The sitting room",
      },
    },
    booking: {
      eyebrow: "Stay with us",
      title: "Send us a message",
      lead: "Have a question or want to check dates? Send a quick note — it reaches us by email and WhatsApp at once, and we'll get back to you.",
      steps: [
        { title: "Send a message", body: "Tell us what you're after — dates, number of guests, or any question." },
        { title: "We reply", body: "We get back to you by email or WhatsApp, usually within a day." },
        { title: "Plan your stay", body: "We sort out the room, the pool, and any extras like the kitchen." },
      ],
      goodToKnow: "Good to know",
      info: {
        poolTitle: "The pool is free", poolDesc: "Included with every booking, day and night.",
        kitchenTitle: "Kitchen on request", kitchenDesc: "Cook your own meals for a small additional amount.",
        locDesc: "Quiet hillside, close to town.",
        talk: "Talk to us",
      },
      form: {
        name: "Your name", namePh: "e.g. Nimal Perera",
        email: "Email",
        checkin: "Check-in", checkout: "Check-out",
        phone: "Phone / WhatsApp", phonePh: "+94 7X XXX XXXX",
        message: "Your message", messagePh: "Number of guests, questions, anything else…",
        newsletter: "Email me occasional offers and news from The Heights Retreat",
        consent: "I'm happy for The Heights Retreat to contact me about this inquiry",
        submit: "Send inquiry", sending: "Sending…",
        openWhatsApp: "Open WhatsApp",
        sendAnother: "Send another message",
        note: "We only use your details to reply. One click also opens WhatsApp with your message ready to send.",
      },
    },
    footer: {
      desc: "A small green homestay in the Kandy hills. A pool, a garden, and a lot of quiet.",
      explore: "Explore", find: "Find us",
      rights: "All rights reserved.",
      bottom: "Drop us a message before you head up.",
    },
    contact: {
      eyebrow: "Find us",
      title: "Come visit",
      lead: "We're on Doolwala Road in Kandy. Call or message any time and we'll help you plan your stay.",
      navLabel: "Contact",
      address: "Address",
      call: "Call us",
      email: "Email",
      whatsapp: "Message on WhatsApp",
      openMaps: "Open in Maps",
    },
  },

  si: {
    code: "si",
    label: "සිං",
    other: "EN",
    nav: { place: "ස්ථානය", amenities: "පහසුකම්", gallery: "ගැලරිය", booking: "වෙන්කිරීම", book: "වෙන්කරවා ගන්න" },
    hero: {
      eyebrow: "මහනුවර · ශ්‍රී ලංකාව",
      titleWords: ["හරිතය", "මැද"],
      titleEm: "අවදි වන්න.",
      lead: "මහනුවර කඳුකරයේ පිහිටි කුඩා නවාතැනක්. ගස් අතරේ එල්ලූ විදුලි පහන් සහිත පිහිනුම් තටාකයක්, පිටුපස බැඩ්මින්ටන් පිටියක්, අවට කොයි පැත්තෙත් හරිතය. දවස් කිහිපයක් නිකම්ම විවේක ගන්න එන්න.",
      chips: { pool: "වෙන්කරවා ගැනීමත් සමඟ තටාකය නොමිලේ", badminton: "බැඩ්මින්ටන් පිටිය", gardens: "උද්‍යාන සහ බිතු සිතුවම්" },
      ctaPrimary: "ලැබෙන දින බලන්න",
      ctaSecondary: "ස්ථානය බලන්න",
      scroll: "පහළට",
    },
    about: {
      eyebrow: "ස්ථානය",
      title: "හරිතයි, නිස්කලංකයි",
      lead: "අපට අවශ්‍ය වුණේ පිටත හරිතය දොරකඩින් නතර නොවන තැනක්. ඒ නිසා කවුළු මත වැල් එල්ලී, රෑට පහන් දැල්වෙයි, සවස් වරුවේ ගස් යට තටාකය එළිය වැටී දිදුලයි.",
      muted: "මේක හිතාමතාම කුඩා තැනක්. කාමර කිහිපයක්, ඇවිදින්න උද්‍යානයක්, උදේට ඔබව අවදි කරන්නේ එලාම් එක නොව කුරුල්ලන් වන තරම් නිස්කලංකයි.",
      points: [
        "බිත්ති මත ගස් සිතුවම්, කොන් කොන්වල පැළ",
        "නවාතැන පුරාම ඔබට අයිති දිගු තටාකයක්, අමතර ගාස්තුවක් නැත",
        "නිදාගන්න පහසු, සිසිල් හරිත කාමර",
        "මහනුවර නගරයේ සිට විනාඩි දහයක් පමණ",
      ],
      tag: "තටාකය අසල සන්ධ්‍යාව",
    },
    amenities: {
      eyebrow: "ඔබට ලැබෙන දේ",
      title: "පහසු නවාතැනකට අවශ්‍ය හැම දේම",
      lead: "තටාකයයි පිටියයි වෙන්කරවා ගැනීමත් සමඟ ලැබෙනවා. ඕන නම් කෑම උයන්න මුළුතැන්ගෙයක් තියෙනවා. ඇත්තටම ඒ ටිකයි.",
      items: [
        { icon: "pool", badgeTone: "good", title: "මිරිදිය තටාකය", badge: "වෙන්කරවා ගැනීමත් සමඟ නොමිලේ", body: "වටේට පහන් එල්ලූ, පිටුපස පොල් ගස් සහිත දිගු තටාකයක්. ඔබේ නවාතැනත් සමඟ නොමිලේ, ඒ නිසා උදේ හයටත් මැදියමටත් කැමති වෙලාවට පිහිනන්න." },
        { icon: "racket", badgeTone: "good", title: "බැඩ්මින්ටන් පිටිය", badge: "ඇතුළත්", body: "පිටුපස විවෘත පිටියක්. රැකට් සහ ෂටල් එක ළඟ තියෙනවා, සවස සිසිල් වුණාම ක්‍රීඩාවක් දාන්න." },
        { icon: "kitchen", badgeTone: "info", title: "හවුල් මුළුතැන්ගෙය", badge: "කුඩා අමතර ගාස්තුවක්", body: "කැමති නම් ඔබේම කෑම උයන්න සම්පූර්ණ මුළුතැන්ගෙයක්. වෙන්කරවා ගන්නකොට අහන්න; කුඩා අමතර මුදලක්. දවස් ගණනක් නවතිනවා නම් ප්‍රයෝජනවත්." },
        { icon: "lantern", badgeTone: "plain", title: "පහන් සහිත කෑම අංගනය", badge: "හැම සැන්දෑවකම", body: "රවුම් වියන ලද පහන් යට වැසුණු අංගනයක්. රෑ කෑමට හෝ කාඩ් සෙල්ලමකට බොහෝ සැන්දෑ ගෙවෙන්නේ මෙතන." },
        { icon: "leaf", badgeTone: "plain", title: "උද්‍යාන සහ සිතුවම්", badge: "හැම තැනම", body: "ගස් සිතුවම්, බඳුන්වල පර්ණ, කොළ අතරට එළිය වැටෙන පහන්. කොයි පැත්ත බැලුවත් හරිතය." },
        { icon: "bed", badgeTone: "plain", title: "හරිත කාමර", badge: "සන්සුන් හා නිස්කලංක", body: "හරිත බිත්ති, මෘදු එළිය, කවුළුව ළඟ වැල් ටිකක්. දවසක් ඇවිද්දට පස්සේ ඕන වෙන සිසිල සහ නිස්කලංකය මේවායේ තියෙනවා." },
      ],
    },
    stats: [
      { to: 6, suffix: "", label: "ඉඩකඩ සහ පහසුකම්" },
      { to: 2, suffix: "", label: "එළිමහන් ක්‍රියාකාරකම්" },
      { to: 100, suffix: "%", label: "හාත්පස හරිතය" },
    ],
    gallery: {
      eyebrow: "අවට බලන්න",
      title: "ස්ථානයේ කොන් කිහිපයක්",
      lead: "සැබෑ ඡායාරූප, ටිකක් එළිය කළා විතරයි. ලොකුවට බලන්න එකක් තට්ටු කරන්න.",
      captions: {
        "pool-twilight": "සැඳෑ ආලෝකයේ තටාකය",
        "pool-fairy-night": "තටාකය මත පහන් එළිය",
        "pool-dusk": "සැඳෑවේ එළිය වැටුණු තටාකය",
        "pool-day": "දිවා කාලයේ තටාකය",
        "pool-night": "තටාකය අසල සන්ධ්‍යාව",
        mural: "සංකේතාත්මක ගස් සිතුවම",
        "room-green": "හරිත කාමරයක්",
        "room-jungle": "වනාන්තර දසුනක් සහිත කාමරයක්",
        "room-pink": "දීප්තිමත් තිර, හරිත බිත්ති",
        "dining-nook": "කෑම කොන",
        dining: "පහන් යට රෑ කෑම",
        "lounge-1": "විවේක ශාලාව",
        "lounge-2": "එකතු වෙන්න ඉඩක්",
        "lounge-3": "වාඩි වෙන කාමරය",
      },
    },
    booking: {
      eyebrow: "අප සමඟ නවතින්න",
      title: "ඔබේ පණිවිඩය එවන්න",
      lead: "ප්‍රශ්නයක් තියෙනවද, නැත්නම් දවස් බලන්න ඕනද? කෙටි පණිවිඩයක් එවන්න — එය එකවර ඊමේල් එකට සහ WhatsApp එකට ලැබෙනවා, අපි ආපහු කතා කරනවා.",
      steps: [
        { title: "පණිවිඩයක් එවන්න", body: "ඔබට අවශ්‍ය දේ — දවස්, අමුත්තන් ගණන, හෝ ඕනෑම ප්‍රශ්නයක් කියන්න." },
        { title: "අපි පිළිතුරු දෙනවා", body: "සාමාන්‍යයෙන් දවසක් ඇතුළත ඊමේල් හෝ WhatsApp මගින් කතා කරනවා." },
        { title: "නවාතැන සැලසුම් කරමු", body: "කාමරය, තටාකය, සහ මුළුතැන්ගෙය වැනි අමතර දේ සකස් කරගමු." },
      ],
      goodToKnow: "දැනගන්න",
      info: {
        poolTitle: "තටාකය නොමිලේ", poolDesc: "හැම වෙන්කරවා ගැනීමකම ඇතුළත්, දවල් රෑ දෙකම.",
        kitchenTitle: "ඉල්ලීම මත මුළුතැන්ගෙය", kitchenDesc: "කුඩා අමතර මුදලකට ඔබේම කෑම උයාගන්න.",
        locDesc: "නිස්කලංක කඳු බෑවුමක්, නගරයට ආසන්නයි.",
        talk: "අප හා කතා කරන්න",
      },
      form: {
        name: "ඔබේ නම", namePh: "උදා: නිමල් පෙරේරා",
        email: "ඊමේල්",
        checkin: "පැමිණෙන දිනය", checkout: "පිටවන දිනය",
        phone: "දුරකථන / WhatsApp", phonePh: "+94 7X XXX XXXX",
        message: "ඔබේ පණිවිඩය", messagePh: "අමුත්තන් ගණන, ප්‍රශ්න, වෙනත් යමක්…",
        newsletter: "The Heights Retreat වෙතින් ඉඳහිට ලැබෙන දීමනා සහ පුවත් ඊමේල් කරන්න",
        consent: "මෙම විමසීම ගැන The Heights Retreat මට සම්බන්ධ වීමට මම කැමතියි",
        submit: "විමසීම යවන්න", sending: "යවමින්…",
        openWhatsApp: "WhatsApp විවෘත කරන්න",
        sendAnother: "තවත් පණිවිඩයක් යවන්න",
        note: "ඔබේ විස්තර භාවිතා කරන්නේ පිළිතුරු දීමට පමණි. එක ක්ලික් එකකින් WhatsApp එකත් විවෘත වෙනවා.",
      },
    },
    footer: {
      desc: "මහනුවර කඳුකරයේ කුඩා හරිත නවාතැනක්. තටාකයක්, උද්‍යානයක්, සහ බොහෝ නිස්කලංකයක්.",
      explore: "ගවේෂණය", find: "අපව හමුවන්න",
      rights: "සියලු හිමිකම් ඇවිරිණි.",
      bottom: "එන්න කලින් අපට පණිවිඩයක් දාන්න.",
    },
    contact: {
      eyebrow: "අපව හමුවන්න",
      title: "අපව බලන්න එන්න",
      lead: "අපි මහනුවර, දූල්වල පාරේ. ඕන වෙලාවක කතා කරන්න හෝ පණිවිඩයක් දාන්න; ඔබේ නවාතැන සැලසුම් කරගන්න උදව් කරනවා.",
      navLabel: "සම්බන්ධතා",
      address: "ලිපිනය",
      call: "අමතන්න",
      email: "ඊමේල්",
      whatsapp: "WhatsApp එකෙන් පණිවිඩයක්",
      openMaps: "සිතියමේ බලන්න",
    },
  },
};
